// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzq9JH2XSN6h-XbtNt0yFEYq3QPYVLAps',
    appId: '1:543058102008:web:d5a1a4fd0d31be5f02dd0d',
    messagingSenderId: '543058102008',
    projectId: 'event-management-system-7894e',
    authDomain: 'event-management-system-7894e.firebaseapp.com',
    storageBucket: 'event-management-system-7894e.appspot.com',
    measurementId: 'G-G1G7H5M5B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtlNfbMpU7r6sL77UlM5U4KlQuinCbQkA',
    appId: '1:543058102008:android:2fd89c1f57d7d38302dd0d',
    messagingSenderId: '543058102008',
    projectId: 'event-management-system-7894e',
    storageBucket: 'event-management-system-7894e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCms-V9EpLQi4_IzS0BMSBvvv6SwzAzhqo',
    appId: '1:543058102008:ios:d23103c57b221f1402dd0d',
    messagingSenderId: '543058102008',
    projectId: 'event-management-system-7894e',
    storageBucket: 'event-management-system-7894e.appspot.com',
    iosClientId: '543058102008-tp48qgh3mbijnfb5rdr1ig8pce1i9ot9.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCms-V9EpLQi4_IzS0BMSBvvv6SwzAzhqo',
    appId: '1:543058102008:ios:b34698611939c4ed02dd0d',
    messagingSenderId: '543058102008',
    projectId: 'event-management-system-7894e',
    storageBucket: 'event-management-system-7894e.appspot.com',
    iosClientId: '543058102008-97ie2bh00a1iibq68qdhrsb63u1f034j.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp.RunnerTests',
  );
}
